FROM node:lts-alpine
ENV NODE_ENV=development
WORKDIR /app
COPY package*.json .
RUN npm ci
# --silent && mv node_modules ../
COPY ./ .
EXPOSE 3000

# RUN chown -R node /usr/src/app
# USER node
CMD ["npm", "start"]
